### ISSUE TITLE
[Esame gennaio 2019] Esercizio 4

### ISSUE THREAD

**Issue by LeoCosta02** [sapienzastudentsnetwork/calcprob2324#119]
L'esercizio dovrebbe essere simile alla tipologia dell'esercizio del foglio 8 es 1 ma con svolgimento simile al foglio 8 es 2 .Non l'ho svolto perchè vorrei prima confrontarmi con voi.
Ci viene dato il valore di lambda= 1000, questo implica che mediamente nella sala da ballo ci sono 1000 persone e il numero di persone è una variabile aleatoria di Poisson come dice nel testo.
Il dubbio riguarda sulla v.a delle persone omosessuali nella stanza che invece dovrebbe essere una v.a di bernoulli che ha parametri (1000,0.05),quindi nel punto 1 e 2 dobbiamo calcolare il valore atteso e la distribuzione di una v.a di bernoulli.
Per quanto riguarda il punto 3 invece credo sia uguale al foglio 8 es 2

**Comment by Elia-Belli** [comment]
@LeoCosta02 è preferibile discutere della soluzione di un determinato esercizio nell'issue di pubblicazione, per mantenere ordine ed evitare la frammentazione del discorso
