### ISSUE TITLE
[Esame 23 gennaio 2019] Esercizio 2

### ISSUE THREAD

**Issue by LeoCosta02** [sapienzastudentsnetwork/calcprob2324#120]
Verificare la correttezza del mio svolgimento

**Comment by CiottoloMaggico** [comment]
Le issue pubblicate da @Elia-Belli relative all'esercizio 2 dell'esame di gennaio 2019 servono proprio a questo... Se nessuno ti risponde probabilmente vuol dire che nessuno lo ha fatto. Non serve creare altre issue....
